### PR TITLE
add plugin support

### PR DESCRIPTION
**Pull request by zbindenren**
The current script does not work with plugins. You get the following error:

```
kubectl sudo <plugin-name> args
Error: unknown command "<plugin-name>" for "kubectl"
Run 'kubectl --help' for usage.
```

### CODE REVIEW

**Comment by djboris9** [comment]
What about cases like this:
```
kubectl sudo get ns
```
where a `kubectl-ns` executable is in the path.

This would evaluate to:
```
+ kubectl ns --as=djboris9 --as-group=system:masters get
Error: unknown flag: --as
```

**Comment by zbindenren** [comment]
OK didn't think about this edge case. Makes script a little more complicated:

```
cat $HOME/bin/kubectl-ns
#!/bin/bash

echo ns
```
```
$ kubectl sudo ns
ns
```
```
$ kubectl sudo ns --arg1 --arg
ns
```
```
$ kubectl sudo get ns |wc -l
22
```

**Comment by schnatterer** [comment]
@zbindenren for the time being you could use a "sudo context" as described in #6 as a workaround

**Comment by djboris9** [comment]
Ooops, this PR got a little bit lost. I will review it this week, maybe today. Thanks @schnatterer for pinging us.

**Review by djboris9 — APPROVED** [review]

**Pull request merged**
